name: ekc_project
description: A new Flutter project.

version: 2.2.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button:
  cached_network_image: ^3.2.0
  file_picker: ^4.2.7
  firebase_storage: ^10.2.3
  http: ^0.13.4
  image_picker: ^0.8.4+4
  mime: ^1.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.8
  url_launcher: ^6.1.2

  flutter_firebase_chat_core: ^1.5.1
  bubble: ^1.2.1


  # FIREBASE PACKAGES
  firebase_analytics: 8.1.0
  cloud_firestore:
  firebase_remote_config:
  firebase_dynamic_links:
  firestore_ui:
  firebase_database:

  faker: ^2.0.0
  firebase_auth:
  firebase_core:
  google_sign_in: ^5.2.1

  flutter_svg: ^1.0.3
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  flutter_chat_ui: ^1.5.3
  stop_watch_timer: ^1.4.0
  #  image_picker: ^0.8.4+4

  cupertino_icons: ^1.0.2
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name:

  flutter_lints: ^1.0.0
#  flutter_launcher_icons:
  flutter_launcher_icons: "^0.9.2"

#  flutter_launcher_name: "^0.0.1"
#flutter_launcher_name:
#  name: "RilTopia"


dependency_overrides:
  flutter_firebase_chat_core: # ^1.5.1
    #    path: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_firebase_chat_core-1.5.1
    path: ./packages/flutter_firebase_chat_core-1.5.1

  flutter_chat_ui:
    path: ./packages/flutter_chat_ui-1.5.8

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/rilMan.riv
    - assets/
    - assets/svg_icons/
    - pubspec.lock
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
assets:
 - Assets/
 - Assets/eks-thumb.jpg
  #   - images/a_dot_ham.jpeg

# flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIconPurple.png"
  #  image_path_android: "assets/android_icon.png"
  #  image_path_ios: "assets/ios_icon.png"


  # example:
  # fonts: # Bahnschrift <<|
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
